yarnPath: .yarn/releases/yarn-3.2.4.cjs

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: ${FONT_AWESOME_PACKAGE_TOKEN}
    npmAlwaysAuth: true